# Travis config for ffcount
#
jobs:
  include:
    - language: python
      dist: xenial
      python: "3.7"
      env:
        - PYTHON="python3"
        - PIP="pip3"
    - os: osx
      language: python
      env:
        - PYTHON="python3"
        - PIP="pip3"
    - os: windows
      language: shell
      before_install:
        - choco install python3 --version 3.6.8 --no-progress -y
      env:
        - PYTHON="python"
        - PIP="pip"

install:
  - $PIP install -e .

script:
  - $PYTHON -m unittest discover -v -f -s ./test
