# Travis config for ffcount
#
jobs:
  include:
    - language: python
      dist: xenial
      python: "3.7"
      env:
        - PYTHON="python3"
        - PIP="pip3"
    - os: osx
      env:
        - PYTHON="python3"
        - PIP="pip3"
    - os: windows
      language: shell
      before_install:
        - choco install python3 --version 3.6.8 --no-progress -y
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - PYTHON="python"
        - PIP="pip"

env:
  global:
    - CIBW_SKIP="cp27-*"

install:
  - $PIP install -e .
  - $PIP install cibuildwheel==1.0.0

script:
  - $PYTHON -m unittest discover -v -f -s ./test
  - cibuildwheel --output-dir wheelhouse
  - ls -1 wheelhouse
