name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 35 8 7,21 * *

jobs:
  python-test:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        py: [ '3.8', '3.13' ] # minimum and latest
    steps:
      - name: Install Python ${{ matrix.py }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Cython
        run: pip install Cython

      - name: Install ffcount
        run: pip install -e .

      - name: Run unit tests
        run: python -m unittest discover -v -f -s ./tests
